// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnwwejjcuwjlbhdgoptb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ud3dlampjdXdqbGJoZGdvcHRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNTUxNjUsImV4cCI6MjA4NTYzMTE2NX0.sQ9f8FfTazhKf97Lk2oUI-MANzyK7zME71ShrAUvVeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});